#! /bin/sh

# Ondřej Štěch's config for bspwm
# based on DistroTubes config  http://www.gitlab.com/dwt1/ 
#        
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

### AUTOSTART ###
sxhkd &
nitrogen --restore &
picom -CGb --config ~/.config/picom.conf  &
nm-applet & # network manager
blueman-applet & # bluetooth
# run power manager only once 
(command -v  xfce4-power-manager && ! pgrep xfce4-power-man) && xfce4-power-manager &
~/.config/polybar/launch.sh &

### MONITORS ###
#bspc monitor eDP1 -n center
#bspc monitor HDMI-1-1 -n right
# workspaces added to each monitor
bspc monitor eDP1 -d 1 2 3 4 5 # laptop monitor
bspc monitor HDMI-1-1 -d 6 7       # second monitor

### BSPWM configuration ###
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20  # needs to be adjusted for polybar
bspc config bottom_padding                0   # needs to be adjusted for polybar
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

### BSPWM coloring ###
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-1-1)

### RULES ###
bspc rule -a Emacs state=tiled
# these are just example rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
